[package]
name = "puzzle-finder"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.7", features = [ "runtime-tokio-native-tls" , "sqlite", "chrono" ] }
tokio = { version = "1.20", features = ["full"] }
chrono = { version = "0.4" }
tiltak = { git = "https://github.com/MortenLohne/tiltak" }
topaz-tak = { git = "https://github.com/MortenLohne/topaz-tak" }
board-game-traits = "0.3.0"
pgn-traits = "0.4.0"
rayon = "1.5"
tokio-stream = "0.1.14"
